# Use an official MySQL runtime as the base image
FROM mysql:latest

# Set the root password for MySQL
# ENV MYSQL_ROOT_PASSWORD=password

# # Create a database and user
ENV MYSQL_DATABASE=LIBRARY

# Copy the SQL script that initializes the database schema
COPY BookLibrary.sql /docker-entrypoint-initdb.d/

# Expose the port on which MySQL will run
EXPOSE 3307
