# Use a Node.js image
FROM node:16

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Expose port 3000
EXPOSE 3000

# Command to start the server
CMD ["npm", "start"]
