# Use a Node.js image
FROM node:18-alpine

# Install nodemon
RUN npm install -g nodemon

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json .

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose port 8020
EXPOSE 8020

# Command to run the server
CMD ["node", "src/components/server.js"]
